# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet Tool
  inputs:
    versionSpec: '4.5'

- task: Bash@3
  displayName: Run Unit and Integration Tests
  inputs:
    targetType: 'inline'
    script: 'make prepare all check CONFIGURATION=Debug'

- task: EsrpCodeSigning@1
  displayName: Sign executable and dll files
  inputs:
    ConnectedServiceName: 'CodeSigning-APEX'
    FolderPath: '$(System.DefaultWorkingDirectory)/api-doc-tools'
    UseMinimatch: true
    signConfigType: inlineSignParams
    SessionTimeout: '60'
    MaxConcurrency: '100'
    MaxRetryAttempts: '5'
    Pattern: |
        api-doc-tools\bin\Release\**\*.dll
        api-doc-tools\bin\Release\**\*.exe
    inlineOperation: |
      [
        {
          "KeyCode": "CP-236167",
          "OperationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd \"SHA256\""
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        },
        {
          "KeyCode": "CP-236167",
          "OperationSetCode": "SigntoolVerify",
          "Parameters": [
            {
              "parameterName": "VerifyAll",
              "parameterValue": "/all"
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        }
      ]


